import { Metadata } from 'next';
import Navigation from './components/navigation';

export const metadata: Metadata = {
  // 타입스크립트에 도움받기 위해 Metadata 사용
  title: {
    template: '%s | NextJS', // app/about/page.tsx 에서 설정한 title을 %s 로 나타난다. -> 'About | NextJS'
    default: 'NextJS', // app/page.tsx 기본 title 설정
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
